#!/usr/bin/env bash
# build-apk.sh — build the Marathon Recompiled Android APK
#
# Stages:
#   1. Ensure Android SDK (platform 34, build-tools 34) is set up
#   2. Attempt native library build via build-android.sh (needs NDK + game files)
#      → skipped gracefully if game files are absent (the APK still builds,
#        just without the game engine library)
#      → skipped entirely when --skip-native is passed (use this in CI after
#        build-android.sh has already run as a separate step)
#   3. Run Gradle assembleDebug to produce the APK
#
# The output APK lands at:
#   android-apk/app/build/outputs/apk/debug/app-debug.apk
#
set -euo pipefail

# CI self-diagnostics: emit the tail of the shared build log as a workflow
# annotation on failure (artifact blobs are not always reachable externally;
# annotations always are).
_ci_fail_trap() {
  local rc=$?
  if [[ $rc -ne 0 && -n "${GITHUB_ACTIONS:-}" ]]; then
    local WORKSPACE_DIR
    WORKSPACE_DIR="$(cd "$(dirname "$0")" && pwd)"
    local LOG="${BUILD_LOG:-$WORKSPACE_DIR/build-logs/build.log}"
    if [[ -f "$LOG" ]]; then
      local ENC
      ENC="$(tail -c 5000 "$LOG" | sed -e 's/%/%25/g' -e 's/\r//g' | awk '{printf "%s%%0A", $0}' | head -c 7000)"
      printf '\n::error title=build-apk.sh exited %d (last log chunk)::%s\n' "$rc" "$ENC"
    fi
  fi
  return 0
}
trap _ci_fail_trap EXIT

# Same channel, but for successful runs: surface key facts about the produced
# APK (which native libs got packaged, compressed or not) so CI runs are
# debuggable without log/artifact blob access.
_ci_notice() {
  if [[ -n "${GITHUB_ACTIONS:-}" ]]; then
    local ENC
    ENC="$(printf '%s' "$2" | sed -e 's/%/%25/g' -e 's/\r//g' | awk '{printf "%s%%0A", $0}' | head -c 7000)"
    printf '\n::notice title=%s::%s\n' "$1" "$ENC"
  fi
}

SKIP_NATIVE=false
BUILD_RELEASE=false
for arg in "$@"; do
  case "$arg" in
    --skip-native) SKIP_NATIVE=true ;;
    --release) BUILD_RELEASE=true ;;
  esac
done

# Default gradle task, overridden to Release when --release is passed.
GRADLE_TASK="assembleDebug"
APK_SUBPATH="debug"
if $BUILD_RELEASE; then
  GRADLE_TASK="assembleRelease"
  APK_SUBPATH="release"
fi

WORKSPACE="$(cd "$(dirname "$0")" && pwd)"
NDK="$WORKSPACE/.ndk-tools/android-ndk-r27c"
SDK="$WORKSPACE/.ndk-tools/android-sdk"
CMDLINE_TOOLS="$SDK/cmdline-tools/latest/bin"

export JAVA_HOME="$(dirname "$(dirname "$(readlink -f "$(which java)")")")"
export ANDROID_HOME="$SDK"
export ANDROID_SDK_ROOT="$SDK"

echo "╔══════════════════════════════════════════════════════════╗"
echo "║        Marathon Recompiled — Android APK Builder         ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  JAVA_HOME:  $JAVA_HOME"
echo "  SDK:        $SDK"
echo "  NDK:        $NDK"
echo ""

# ── Stage 1: Android SDK setup ─────────────────────────────────────────────────
echo "▶ Stage 1: Android SDK"

if [[ ! -f "$CMDLINE_TOOLS/sdkmanager" ]]; then
  echo "  Downloading Android command-line tools..."
  mkdir -p "$SDK/cmdline-tools"
  curl -sL -o /tmp/cmdline-tools.zip \
    "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
  unzip -q /tmp/cmdline-tools.zip -d /tmp/cmdline-tools-tmp
  mv /tmp/cmdline-tools-tmp/cmdline-tools "$SDK/cmdline-tools/latest"
  rm -rf /tmp/cmdline-tools.zip /tmp/cmdline-tools-tmp
  echo "  Command-line tools installed."
fi

PLATFORM_DIR="$SDK/platforms/android-34"
BUILD_TOOLS_DIR="$SDK/build-tools/34.0.0"

if [[ ! -d "$PLATFORM_DIR" ]] || [[ ! -d "$BUILD_TOOLS_DIR" ]]; then
  echo "  Installing Android platform 34 + build-tools 34.0.0..."
  yes | "$CMDLINE_TOOLS/sdkmanager" \
    --sdk_root="$SDK" \
    "platforms;android-34" \
    "build-tools;34.0.0" \
    2>&1 | grep -v "^\[=" | grep -v "^$" || true
  echo "  SDK components installed."
else
  echo "  SDK components already present. Skipping download."
fi

# Write/update local.properties for Gradle
cat > "$WORKSPACE/android-apk/local.properties" <<EOF
# Auto-generated by build-apk.sh — do not edit manually.
sdk.dir=$SDK
ndk.dir=$NDK
EOF
echo "  local.properties updated."
echo ""

# ── Stage 2: Native library (optional — needs game files) ─────────────────────
echo "▶ Stage 2: Native library (libmain.so)"

# Real game files live in AppStorage (runtime), not in the APK assets.
# For the build we check if the private game data path exists.
PRIVATE_XEX="$WORKSPACE/MarathonRecompLib/private/default.xex"
JNI_LIB="$WORKSPACE/android-apk/app/jniLibs/arm64-v8a/libmain.so"
OLD_JNI_SHA=""
if [[ -f "$JNI_LIB" ]]; then
  OLD_JNI_SHA="$(sha256sum "$JNI_LIB" | awk '{print $1}')"
fi

if $SKIP_NATIVE; then
  echo "  --skip-native passed: native build already done; using existing libmain.so."
  if [[ ! -f "$JNI_LIB" ]]; then
    echo "  ✘ --skip-native set but $JNI_LIB is missing — did build-android.sh run?"
    exit 1
  fi
elif [[ -f "$PRIVATE_XEX" ]] && [[ -d "$NDK" ]]; then
  echo "  Game files found — running native build..."
  if $BUILD_RELEASE; then
    NATIVE_ARGS="--release"
  else
    NATIVE_ARGS=""
  fi
  if ! bash "$WORKSPACE/build-android.sh" $NATIVE_ARGS; then
    echo "  ✘ Native build failed; refusing to package a stale libmain.so."
    exit 1
  fi
  if [[ ! -f "$JNI_LIB" ]]; then
    echo "  ✘ Native build completed without producing $JNI_LIB."
    exit 1
  fi
elif [[ ! -d "$NDK" ]]; then
  echo "  ⚠ NDK not found at $NDK — skipping native build."
  echo "    To download: mkdir -p .ndk-tools && cd .ndk-tools && \\"
  echo "      curl -sL -o ndk.zip https://dl.google.com/android/repository/android-ndk-r27c-linux.zip && \\"
  echo "      unzip -q ndk.zip && rm ndk.zip"
else
  echo "  ℹ Game files not present (MarathonRecompLib/private/default.xex)"
  echo "    Native library will be skipped — APK will contain launcher + settings only."
  echo "    Supply your Xbox 360 game dump and re-run to produce the full APK."
fi

JNI_BYTES=0
JNI_SHA="absent"
if [[ -f "$JNI_LIB" ]]; then
  JNI_BYTES="$(stat -c '%s' "$JNI_LIB")"
  JNI_SHA="$(sha256sum "$JNI_LIB" | awk '{print $1}')"
  echo "  ✔ libmain.so: ${JNI_BYTES} bytes"
  echo "    SHA-256: $JNI_SHA"
  if [[ -n "$OLD_JNI_SHA" && "$OLD_JNI_SHA" == "$JNI_SHA" ]]; then
    echo "    Native bytes are unchanged from the previous build."
  fi
else
  echo "  ✘ libmain.so absent — launching/settings will work, game will not start."
fi
echo ""

# ── Stage 3: Gradle APK build ─────────────────────────────────────────────────
echo "▶ Stage 3: Gradle $GRADLE_TASK"

cd "$WORKSPACE/android-apk"
chmod +x gradlew

# Old gradle outputs/intermediates were accidentally committed to the repo at
# some point; wipe them so packaging can never pick up stale state.
rm -rf "$WORKSPACE/android-apk/app/build" "$WORKSPACE/android-apk/.gradle"

export PATH="$SDK/build-tools/34.0.0:$SDK/platform-tools:$PATH"

# For one-click Release without secrets: if user asked for --release but did not provide
# a CI keystore via env vars, generate a local debug keystore for signing the release APK
# so it is installable out of the box (same as debug). Real Play Store releases should
# supply ANDROID_KEYSTORE_* env vars as in .github/workflows/build-apk.yml.
if $BUILD_RELEASE && [[ -z "${ANDROID_KEYSTORE_FILE:-}" ]]; then
  DEBUG_KEYSTORE="$HOME/.android/debug.keystore"
  if [[ ! -f "$DEBUG_KEYSTORE" ]]; then
    echo "  No keystore supplied, generating temporary debug keystore for Release signing..."
    mkdir -p "$(dirname "$DEBUG_KEYSTORE")"
    keytool -genkey -v -keystore "$DEBUG_KEYSTORE" -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US" >/dev/null 2>&1 || true
  fi
  # Create a local gradle.properties that points signing to debug keystore if no CI keystore
  if [[ ! -f "$WORKSPACE/android-apk/app/release-signing.properties" ]]; then
    cat > "$WORKSPACE/android-apk/app/release-signing.properties" <<PROP
# Auto-generated by build-apk.sh --release for one-click installable Release APK
# Delete this file if you want to use your own keystore via ANDROID_KEYSTORE_* env.
storeFile=$DEBUG_KEYSTORE
storePassword=android
keyAlias=androiddebugkey
keyPassword=android
PROP
    echo "  Release will be signed with debug keystore at $DEBUG_KEYSTORE (one-click mode)"
  fi
  # Inject signing config into build.gradle if not already present
  if ! grep -q "release-signing.properties" "$WORKSPACE/android-apk/app/build.gradle"; then
    echo "  (release-signing.properties will be picked up if you add a signingConfigs block that reads it)"
  fi
fi

./gradlew $GRADLE_TASK \
  --no-daemon \
  --rerun-tasks \
  --stacktrace \
  2>&1

APK="$WORKSPACE/android-apk/app/build/outputs/apk/$APK_SUBPATH/app-$APK_SUBPATH.apk"
# Fallback for release with debug keystore name variant
if [[ ! -f "$APK" ]]; then
  # Gradle may output app-release-unsigned.apk when signing is not configured, try that
  ALT_APK="$WORKSPACE/android-apk/app/build/outputs/apk/$APK_SUBPATH/app-$APK_SUBPATH-unsigned.apk"
  if [[ -f "$ALT_APK" ]]; then
    APK="$ALT_APK"
  fi
fi

echo ""
if [[ -f "$APK" ]]; then
  APK_BYTES="$(stat -c '%s' "$APK")"
  APK_SHA="$(sha256sum "$APK" | awk '{print $1}')"
  PACKAGED_LIB_BYTES=0
  PACKAGED_LIB_SHA="absent"
  if [[ -f "$JNI_LIB" ]] && unzip -l "$APK" 'lib/arm64-v8a/libmain.so' >/dev/null 2>&1; then
    PACKAGED_LIB_BYTES="$(unzip -p "$APK" 'lib/arm64-v8a/libmain.so' | wc -c | tr -d ' ')"
    PACKAGED_LIB_SHA="$(unzip -p "$APK" 'lib/arm64-v8a/libmain.so' | sha256sum | awk '{print $1}')"
  fi
  echo "╔══════════════════════════════════════════════════════════╗"
  echo "║  ✔  BUILD SUCCESSFUL                                     ║"
  echo "╠══════════════════════════════════════════════════════════╣"
  printf "║  APK:  %-49s ║\n" "android-apk/app/build/outputs/apk/$APK_SUBPATH/"
  printf "║  File: %-49s ║\n" "app-$APK_SUBPATH.apk  (${APK_BYTES} bytes)"
  echo "╚══════════════════════════════════════════════════════════╝"
  echo "  APK SHA-256: $APK_SHA"
  echo "  Packaged ARM64 libmain.so: ${PACKAGED_LIB_BYTES} bytes"
  echo "  Packaged ARM64 lib SHA-256: $PACKAGED_LIB_SHA"

  # Surface the native-lib packaging facts as a workflow annotation so CI runs
  # are inspectable without artifact/log access. If the packaged lib differs
  # from the staged one (size+sha), Gradle stripped it — that is fine for
  # running, but good to know when comparing builds.
  APK_LIB_REPORT="$(
    echo "APK: ${APK_BYTES} bytes, sha256 $APK_SHA"
    echo "staged  libmain.so: ${JNI_BYTES} bytes, sha256 $JNI_SHA"
    echo "packaged lib/arm64-v8a/libmain.so: ${PACKAGED_LIB_BYTES} bytes, sha256 $PACKAGED_LIB_SHA"
    echo "--- merged manifest facts ---"
    AAPT2="$(find "$SDK/build-tools" -name aapt2 -type f 2>/dev/null | head -1)"
    if [[ -n "$AAPT2" ]]; then
      "$AAPT2" dump packagename "$APK" 2>/dev/null
      "$AAPT2" dump xmltree --file AndroidManifest.xml "$APK" 2>/dev/null \
        | grep -iE 'extractNativeLibs|versionName' | head -5
    else
      echo "aapt2 not found under $SDK/build-tools"
    fi
    echo "--- lib/ entries in APK (uncompressed_bytes method compressed_bytes name) ---"
    unzip -lv "$APK" 'lib/*' 2>/dev/null | grep -E ' lib/' | awk '{print $1, $2, $3, $8}' | head -40
  )"
  echo "$APK_LIB_REPORT"
  _ci_notice "APK native libraries" "$APK_LIB_REPORT"

  # Hard gate: if build-android.sh staged a libmain.so for packaging, the APK
  # MUST contain it. (Previously gated on "! --skip-native", which is exactly
  # backwards: --skip-native is the CI path where the staged lib exists and
  # packaging must be verified.)
  if [[ "$PACKAGED_LIB_BYTES" -eq 0 ]] && [[ -f "$JNI_LIB" ]]; then
    echo ""
    echo "✘ FATAL: staged libmain.so exists but the APK does NOT contain lib/arm64-v8a/libmain.so" >&2
    echo "  jniLibs staging: $JNI_LIB ($JNI_BYTES bytes)" >&2
    echo "  Check the Gradle sourceSets jniLibs.srcDirs / packagingOptions wiring." >&2
    exit 1
  fi
else
  echo "╔══════════════════════════════════════════════════════════╗"
  echo "║  ✘  BUILD FAILED — APK not produced                     ║"
  echo "╚══════════════════════════════════════════════════════════╝"
  exit 1
fi
